export function resolveDomElements(documentRef = document) {
  const appRoot = documentRef.documentElement;

  return {
    worldCanvas: documentRef.getElementById("viewport"),
    spriteCanvas: documentRef.getElementById("sprite-layer"),
    status: documentRef.getElementById("status"),
    mount: documentRef.getElementById("game-stage"),
    renderFrame: documentRef.getElementById("render-frame"),
    jitterSlider: documentRef.getElementById("jitter-slider"),
    jitterValue: documentRef.getElementById("jitter-value"),
    warmOverlay: documentRef.getElementById("warm-overlay"),
    hudInstructions: documentRef.getElementById("hud-instructions"),
    hudContext: documentRef.getElementById("hud-context"),
    hudChecklist: documentRef.getElementById("hud-checklist"),
    hudMeta: documentRef.getElementById("hud-meta"),
    missionsStack: documentRef.getElementById("missions-stack"),
    questFocusTitle: documentRef.getElementById("quest-focus-title"),
    questFocusBody: documentRef.getElementById("quest-focus-body"),
    nearbyHabitatsValue: documentRef.getElementById("nearby-habitats-value"),
    bagOnboardingTitle: documentRef.getElementById("bag-onboarding-title"),
    bagOnboardingBody: documentRef.getElementById("bag-onboarding-body"),
    bagDetailsIcon: documentRef.getElementById("bag-details-icon"),
    bagDetailsName: documentRef.getElementById("bag-details-name"),
    bagDetailsCount: documentRef.getElementById("bag-details-count"),
    bagDetailsDescription: documentRef.getElementById("bag-details-description"),
    inventoryGrid: documentRef.getElementById("inventory-grid"),
    skillsPanel: documentRef.getElementById("skills-panel"),
    skillsGrid: documentRef.getElementById("skills-grid"),
    builderPanel: documentRef.getElementById("builder-panel"),
    uiLayer: documentRef.getElementById("ui-layer"),
    hudPanel: documentRef.getElementById("hud-panel"),
    questFocusPanel: documentRef.getElementById("quest-focus-panel"),
    missionsPanel: documentRef.getElementById("missions-panel"),
    inventoryPanel: documentRef.getElementById("inventory-panel"),
    startOverlay: documentRef.getElementById("start-overlay"),
    sceneTransitionVeil: documentRef.getElementById("scene-transition-veil"),
    introOverlay: documentRef.getElementById("intro-overlay"),
    introRoomDebugRoot: documentRef.getElementById("intro-room-debug-root"),
    pauseOverlay: documentRef.getElementById("pause-overlay"),
    cinematicOverlay: documentRef.getElementById("cinematic-overlay"),
    tutorialOverlay: documentRef.getElementById("tutorial-overlay"),
    pokedexAlertButton: documentRef.getElementById("pokedex-alert"),
    pokedexOverlay: documentRef.getElementById("pokedex-overlay"),
    appRoot,
    rootStyle: appRoot.style
  };
}
