import { INTERACTABLE_DEFS } from "../../gameplayContent.js";
import { createResourceNodes } from "../../world/islandWorld.js";
import { createSnowstormParticleField } from "./snowstormParticleField.js";

export function createEmptySession() {
  return {
    bulbasaurEncounter: null,
    bulbasaurLeafageAction: null,
    bulbasaurTexture: null,
    charmanderEncounter: null,
    charmanderTexture: null,
    actTwoRepairPlant: null,
    actTwoSquirtle: null,
    beeInstances: [],
    beeModel: null,
    beePatrolState: null,
    billCameo: null,
    characterTextures: {},
    chopperNpcActor: null,
    challengeBoulder: null,
    challengeBoulderTexture: null,
    colliderGizmoTextures: null,
    campfire: null,
    campfireTrainHouseModelInstance: null,
    campfireTexture: null,
    deadFlowerTexture: null,
    deadGrassTexture: null,
    dittoFlag: null,
    dittoFlagTexture: null,
    elevatedTerrainColliders: [],
    elevatedTerrainInstances: [],
    greenFlowerTexture: null,
    greenGrassTexture: null,
    groundDeadInstances: [],
    groundFlowerPatches: [],
    groundGrassPatches: [],
    iceGroundInstances: [],
    groundPurifiedInstances: [],
    gameplayOpeningRequested: false,
    gameplayOpeningShip: null,
    gameplayOpeningShipFlashTexture: null,
    gameplayOpeningShipSmokeTexture: null,
    gameplayOpeningShipTexture: null,
    interactables: INTERACTABLE_DEFS.map((interactable) => ({ ...interactable })),
    leppaBerryDrops: [],
    leppaBerryTexture: null,
    leppaTree: null,
    leafDen: null,
    leafDenFurniture: [],
    leafDenKitTexture: null,
    leafDenTexture: null,
    leavesTexture: null,
    logChair: null,
    logChairTexture: null,
    markerTextures: {},
    natureRevivalEffects: null,
    natureRevivalSparkTexture: null,
    npcActors: [],
    palmInstances: [],
    palmModel: null,
    playerCharacter: null,
    playerModelInstance: null,
    playerDust: null,
    playerDustTexture: null,
    pokemonCenterPc: null,
    pokemonCenterPcTexture: null,
    repairPlantBrokenTexture: null,
    repairPlantFixedTexture: null,
    resourceNodes: createResourceNodes(),
    sceneObjects: [],
    skyTexture: null,
    snowflakeTexture: null,
    snowstorm: createSnowstormParticleField(),
    spawnActTwoPlayer: () => {},
    strawBed: null,
    strawBedTexture: null,
    squirtleWaterGunAction: null,
    squirtleWaterGunQueue: [],
    squirtleWaterStamina: null,
    squirtleWaterStaminaBackTexture: null,
    squirtleWaterStaminaFillTexture: null,
    charmanderCarbonEnergy: null,
    charmanderCarbonFillTexture: null,
    squirtleChargingParticleTexture: null,
    squirtleWaterSprayTexture: null,
    leafageGardenInstances: [],
    leafageGardenModel: null,
    tallGrassInstances: [],
    tallGrassModel: null,
    timburrEncounter: null,
    timburrTexture: null,
    woodDrops: [],
    woodTexture: null
  };
}
