import { INTERACTABLE_DEFS } from "../../gameplayContent.js";
import { createResourceNodes } from "../../world/islandWorld.js";

export function createEmptySession() {
  return {
    bulbasaurEncounter: null,
    bulbasaurTexture: null,
    charmanderEncounter: null,
    charmanderTexture: null,
    actTwoPokedexCache: null,
    actTwoRepairPlant: null,
    actTwoSquirtle: null,
    characterTextures: {},
    chopperNpcActor: null,
    challengeBoulder: null,
    challengeBoulderTexture: null,
    colliderGizmoTextures: null,
    campfire: null,
    campfireTexture: null,
    deadFlowerTexture: null,
    deadGrassTexture: null,
    dittoFlag: null,
    dittoFlagTexture: null,
    elevatedTerrainColliders: [],
    elevatedTerrainInstances: [],
    greenFlowerTexture: null,
    greenGrassTexture: null,
    groundDeadInstances: [],
    groundFlowerPatches: [],
    groundGrassPatches: [],
    groundPurifiedInstances: [],
    gameplayOpeningRequested: false,
    gameplayOpeningShip: null,
    gameplayOpeningShipFlashTexture: null,
    gameplayOpeningShipSmokeTexture: null,
    gameplayOpeningShipTexture: null,
    interactables: INTERACTABLE_DEFS.map((interactable) => ({ ...interactable })),
    leppaBerryDrops: [],
    leppaBerryTexture: null,
    leppaTree: null,
    leafDen: null,
    leafDenFurniture: [],
    leafDenKitTexture: null,
    leafDenTexture: null,
    logChair: null,
    logChairTexture: null,
    markerTextures: {},
    natureRevivalEffects: null,
    natureRevivalSparkTexture: null,
    npcActors: [],
    palmInstances: [],
    palmModel: null,
    playerCharacter: null,
    playerDust: null,
    playerDustTexture: null,
    pokemonCenterPc: null,
    pokemonCenterPcTexture: null,
    pokedexCacheTexture: null,
    repairPlantBrokenTexture: null,
    repairPlantFixedTexture: null,
    resourceNodes: createResourceNodes(),
    sceneObjects: [],
    skyTexture: null,
    spawnActTwoPlayer: () => {},
    strawBed: null,
    strawBedTexture: null,
    squirtleWaterGunAction: null,
    squirtleWaterGunQueue: [],
    squirtleWaterSprayTexture: null,
    tallGrassInstances: [],
    tallGrassModel: null,
    timburrEncounter: null,
    timburrTexture: null,
    woodDrops: [],
    woodTexture: null
  };
}
