export const ROBOT_IDLE_PATROL_RADIUS_MULTIPLIER = 6;
export const SQUIRTLE_IDLE_PATROL_RADIUS = 0.58 * ROBOT_IDLE_PATROL_RADIUS_MULTIPLIER;
export const BULBASAUR_IDLE_PATROL_RADIUS = 0.68 * ROBOT_IDLE_PATROL_RADIUS_MULTIPLIER;
